name: hc_4
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  change_app_package_name: ^1.4.0
  custom_progressbar: ^0.0.2
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  easy_date_timeline: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  intl: ^0.19.0
  webview_flutter: ^4.10.0
  pull_down_button: ^0.10.2
  flutter_svg: ^2.0.14
  provider: ^6.0.0
  flagsmith: ^6.0.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  get_ip_address: ^0.0.7
  http: ^1.2.2
  webview_flutter_wkwebview: ^3.16.2
  shared_preferences: ^2.3.3
  in_app_review: ^2.0.9
  flutter_email_sender: ^6.0.3
  gaimon: ^1.3.2
  flutter_app_info: 
  is_first_run: ^1.0.0
  connectivity_plus: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      remove_alpha_ios: true
      image_path: "assets/images/icon.png"
      min_sdk_android: 24 # android min sdk min:16, default 21
      adaptive_icon_background: "#4A4A4C" # You can use a color or image for the background
      adaptive_icon_foreground: "assets/images/icon.png" # For adaptive icons on Android

flutter_native_splash:
  color: "#010101"
  image: assets/images/icon.png
  android_12: 
    image: assets/images/icon.png
    color: "#010101"

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProText-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
